version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - $HOME/$USER/data:/var/lib/nginx/html

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    # ports:
    #   - "9000:9000"
    volumes:
      - $HOME/$USER/data:/var/lib/nginx/html
