# This is a default site configuration which will simply return 404, preventing
# chance access to any other virtualhost.

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # Document root
    root /var/lib/nginx/html;

    # Add index.php if using PHP
    index index.php index.htm index.html;

    server_name _;

    # Serve static files or fallback to 404
    location / {
        try_files $uri $uri/ =404;
    }

    # Pass PHP scripts to PHP-FPM
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_index index.php;
        # Assuming PHP-FPM socket in Alpine
        # fastcgi_pass unix:/var/run/php-fpm.sock;
		fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Deny access to hidden files like .htaccess
    location ~ /\. {
        deny all;
    }
}

# Example virtual host (commented out)
# server {
#     listen 80;
#     listen [::]:80;
#     server_name example.com;
#     root /var/lib/nginx/example.com;
#     index index.html index.php;
#     location / {
#         try_files $uri $uri/ =404;
#     }
# }

